### ISSUE TITLE
Add support for autopep8

### ISSUE THREAD

**Issue by roskakori** [roskakori/shapiro#25]
Goal: minor formatting mistakes are automatically fixed during commit.

This needs autopep8. Installation:
```
conda install -c conda-forge autopep8
```

Then there is also a pre commit hook:
```yaml
-   id: autopep8-wrapper
    name: autopep8 wrapper
    description: "Runs autopep8 over python source.  If you configure additional arguments you'll want to at least include -i."
    entry: autopep8-wrapper
    language: python
    types: [python]
    args: [-i]
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 0.15.0
```
