### ISSUE TITLE
Define branching guidelines

### ISSUE THREAD

**Issue by roskakori** [roskakori/shapiro#26]
Currently all commits go to the `master`. In future it might be useful to have a more defensive branching strategy to make merging more robust and limit the impact of accidental screw ups.

Example: [Gitflow workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)

There's a pre commit hook to help with that:
```yaml
-   id: no-commit-to-branch
    name: "Don't commit to branch"
    entry: no-commit-to-branch
    language: python
    pass_filenames: false
    always_run: true
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 0.15.0
```
